---
dist: xenial
language: ruby
python: 3.8
cache: bundler
jdk: openjdk11
rvm:
  #  - 2.7.1
  - jruby-9.2.13.0

before_install:
  - wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py --user
  - python3 -m pip install --user git+https://github.com/klobuczek/boltkit@1.3#egg=boltkit
  - neoctrl-install $NEO4J_EDITION_FLAG $NEO4J_VERSION servers
  - if [ -n "$NEO4J_EDITION_FLAG" ]; then NEO4J_EDITION=enterprise; else NEO4J_EDITION=community; fi
  - NEO4J_DIR=servers/neo4j-$NEO4J_EDITION-$NEO4J_VERSION
  - neoctrl-configure $NEO4J_DIR dbms.memory.pagecache.size=600m dbms.memory.heap.max_size=600m dbms.memory.heap.initial_size=600m dbms.directories.import=
  #dbms.connectors.default_listen_address=::
install:
  - neoctrl-set-initial-password password $NEO4J_DIR
  - neoctrl-start $NEO4J_DIR
  - wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-16.04.deb
  - sudo dpkg -i seabolt-1.7.4-Linux-ubuntu-16.04.deb
  - bundle install --jobs=3 --retry=3

env:
  global:
    - JRUBY_OPTS="--debug -J-Xmx1280m -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF"
    - NEO4J_URL="bolt://localhost:7687"
  matrix:
    - NEO4J_VERSION=3.5.22
    - NEO4J_VERSION=4.0.8
    - NEO4J_VERSION=4.1.1
    #matrix:
    #  include:
    # Testing older versions of ActiveModel
#    - rvm: 2.5.8
#      jdk: openjdk8
#      env: NEO4J_VERSION=community-3.4.18 ACTIVE_MODEL_VERSION=5.2.3

#    - rvm: jruby-9.2.11.1
#      env: driver=java NEO4J_VERSION=enterprise-4.0.8
#    - rvm: jruby-9.2.13.0
#      env: driver=java NEO4J_VERSION=enterprise-4.0.8
#    - rvm: jruby-9.2.11.1
#      env: driver=java NEO4J_VERSION=enterprise-4.1.1
#    - rvm: jruby-9.2.13.0
#      env: driver=java NEO4J_VERSION=enterprise-4.1.1
